'use strict';

const CATALOG_CODES = Object.freeze({
  DISABLED: 'CATALOG_DISABLED',
  PATH_MISSING: 'CATALOG_PATH_MISSING',
  READ_FAILED: 'CATALOG_READ_FAILED',
  TOO_LARGE: 'CATALOG_TOO_LARGE',
  INVALID_JSON: 'CATALOG_INVALID_JSON',
  INVALID_ROOT: 'CATALOG_INVALID_ROOT',
  UNSUPPORTED_VERSION: 'CATALOG_UNSUPPORTED_VERSION',
  LIMIT_EXCEEDED: 'CATALOG_LIMIT_EXCEEDED',
  INVALID_SOURCE: 'CATALOG_INVALID_SOURCE',
  INVALID_RESOLVER: 'CATALOG_INVALID_RESOLVER',
  DUPLICATE_SOURCE: 'CATALOG_DUPLICATE_SOURCE',
  DUPLICATE_RESOLVER: 'CATALOG_DUPLICATE_RESOLVER',
  MISSING_SECRET: 'CATALOG_MISSING_SECRET',
});

const catalogError = (code) => Object.assign(new Error(code), { code });

module.exports = { CATALOG_CODES, catalogError };
