'use strict';

const SOURCE_PROVIDER_ERROR_CODES = Object.freeze({
  INVALID_INPUT: 'SOURCE_PROVIDER_INVALID_INPUT',
  INVALID_PROVIDER: 'SOURCE_PROVIDER_INVALID_PROVIDER',
  DUPLICATE_PROVIDER: 'SOURCE_PROVIDER_DUPLICATE_ID',
  ABORTED: 'SOURCE_PROVIDER_ABORTED',
  TIMEOUT: 'SOURCE_PROVIDER_TIMEOUT',
  INVALID_RESULT: 'SOURCE_PROVIDER_INVALID_RESULT',
  FAILED: 'SOURCE_PROVIDER_FAILED',
  GLOBAL_TIMEOUT: 'SOURCE_PROVIDER_GLOBAL_TIMEOUT',
});

const sourceProviderError = (code) => {
  const error = new Error(code);
  error.code = code;
  return error;
};

module.exports = { SOURCE_PROVIDER_ERROR_CODES, sourceProviderError };
